########################################
# Packages & Utilities (common)
########################################

brew "atuin"
brew "bat"
brew "btop"
brew "clipboard"
brew "curl"
brew "direnv"
brew "eza"
brew "fd"
brew "figlet"
brew "fish"
brew "fzf"
brew "gawk"
brew "gcc"
# brew "git"
brew "git-delta"
brew "gh"
brew "just"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "make"
brew "mise"
brew "nushell"
brew "nvim"
brew "pass"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "topgrade"
brew "trash-cli"
brew "tree"
brew "tree-sitter-cli"
brew "uv"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"

# AI / coding assistants
brew "aider"
tap  "charmbracelet/tap"
brew "charmbracelet/tap/crush"
cask "claude-code"
brew "gemini-cli"
brew "opencode"


# Fonts
# https://formulae.brew.sh/cask-font/
# tap  "homebrew/cask-fonts"
# cask "font-blex-mono-nerd-font"
cask "font-caskaydia-cove-nerd-font"
cask "font-caskaydia-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
# cask "font-terminess-ttf-nerd-font"

########################################
#+ Platform-specific (leave as-is)
########################################
if OS.linux?
  brew "podman"
end

########################################
# macOS Only
########################################
if OS.mac?
  cask "raycast"

  cask "brave-browser"
  cask "google-chrome"

  cask "ghostty"
  cask "warp"

  cask "obsidian"
  cask "visual-studio-code"
  cask "zed"

  cask "podman-desktop"
end
